name = "ComoniconOptions"
uuid = "a25bc8ac-9d24-42b2-8edd-3d267ec19fc5"
authors = ["Roger-Luo <rogerluo.rl18@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Configurations = "5218b696-f38b-4ac9-8b61-a12ec717816d"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
Configurations = "0.15"
julia = "1.6.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
